export const QUERY_KEYS = {
  BENEFICIARIES: 'beneficiaries',
  BENEFICIARY: 'beneficiary',
  PRODUCTS: 'products',
  PRODUCT: 'product',
  INVENTORY: 'inventory',
  INVENTORIES: 'inventories',
  INVENTORY_ITEMS: 'inventoryItems',
  NEW_INVENTORY_ITEM: 'newInventoryItem',
  INSTITUTIONS: 'institutions',
  INSTITUTION: 'institution',
  MEDICAL_SPECIALISTS: 'medicalSpecialists',
  ITEM_BY_BARCODE: 'itemByBarcode',
  TICKET_HISTORY: 'ticketHistory',
};
